//
//  SearchBarPlugin.swift
//
//  Created by Crystal To on 2016-09-06.
//  Copyright (c) 2016 Mobify. All rights reserved.
//

import Foundation
import UIKit
import Astro

public class SearchBarPlugin: Plugin, ViewPlugin, UISearchBarDelegate, LocaleChangedListener {
    public let viewController = UIViewController()
    let searchBar = UISearchBar()
    
    public required init(address: MessageAddress, messageBus: MessageBus, pluginResolver: PluginResolver, options: JsonObject?) {
        super.init(address: address, messageBus: messageBus, pluginResolver: pluginResolver, options: options)
        
        self.addRpcMethodShim("blur") { params, respond in
            ////////// This will be autogenerated at some point //////////
            self.blur(respond)
            /////////////////////////////////////////////////////////////
        }
        
        self.addRpcMethodShim("focus") { params, respond in
            ////////// This will be autogenerated at some point //////////
            self.focus(respond)
            /////////////////////////////////////////////////////////////
        }
        
        self.addRpcMethodShim("setText") { params, respond in
            ////////// This will be autogenerated at some point //////////
            if let text: String = MethodShimUtils.getArg(params, key: "text", respond: respond) {
                self.setText(text, respond: respond)
            }
            /////////////////////////////////////////////////////////////
        }

        Localization.addLocaleChangedListener(self)
        searchBar.delegate = self
        searchBar.translucent = true
        searchBar.showsCancelButton = true
        setLocalizedText()
        searchBar.translatesAutoresizingMaskIntoConstraints = false
        viewController.view.addSubview(searchBar)
        searchBar.pinToSuperviewEdges()
    }
    
    public func searchBarSearchButtonClicked(searchBar: UISearchBar) {
        trigger("search:submitted", params:["searchTerms": searchBar.text!])
    }
    
    public func searchBarCancelButtonClicked(searchBar: UISearchBar) {
        trigger("search:cancelled")
    }

    func blur(respond: RpcMethodCallback) {
        searchBar.resignFirstResponder()
    }
    
    func focus(respond: RpcMethodCallback) {
        searchBar.becomeFirstResponder()
    }
    
    func setText(text: String, respond: RpcMethodCallback) {
        searchBar.text = text
    }
    
    func setLocalizedText() {
        searchBar.placeholder = Localization.translate("search_bar_hint")
    }

    public func localeDidChange() {
        setLocalizedText()
    }
}